# Generated by Django 3.2.5 on 2021-08-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('WAIT', 'Tamir Bekliyor'), ('FIXING', 'Tamir Ediliyor'), ('FIXED', 'Tamir Edildi')], default='WAIT', max_length=10),
        ),
    ]
